# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-05-20 12:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('writing', '0002_auto_20160520_1017'),
    ]

    operations = [
        migrations.AddField(
            model_name='writing',
            name='title',
            field=models.CharField(default='', max_length=255),
            preserve_default=False,
        ),
    ]
