# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-05-20 12:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('writing', '0003_writing_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='writing',
            name='active',
            field=models.BooleanField(default=False),
        ),
    ]
