# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-05-21 10:39
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('writing', '0004_writing_active'),
    ]

    operations = [
        migrations.CreateModel(
            name='View',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name=b'date created')),
            ],
        ),
        migrations.AlterModelOptions(
            name='writing',
            options={'ordering': ['id']},
        ),
        migrations.AddField(
            model_name='view',
            name='writing',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='writing.Writing'),
        ),
    ]
